apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: HEAD
    path: nginx1

  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: nginx1
  
  syncPolicy:
    {{- .Values.spec.syncPolicy | toYaml | nindent 4 }}